((Monky1 monkey-location t5-7 monkey-on-top-of green-couch monkey-holding blank)
  (thi1 thing-name green-couch thing-location t5-7 thing-weight heavy thing-on-top-of floor)
  (thi2 thing-name red-couch thing-location t2-2 thing-weight heavy thing-on-top-of floor)
  (thi3 thing-name big-pillow thing-location t2-2 thing-on-top-of red-couch thing-weight light)
  (thi4 thing-name red-chest thing-location t2-2 thing-on-top-of big-pillow thing-weight light)
  (che1 chest-name red-chest chest-contents ladder chest-unlocked-by red-key)
  (thi5 thing-name blue-chest thing-location t7-7 thing-on-top-of ceiling thing-weight light)
  (che2 chest-name blue-chest chest-contents bananas chest-unlocked-by blue-key)
  (thi6 thing-name blue-couch thing-location t8-8 thing-weight heavy thing-on-top-of floor)
  (thi7 thing-name green-chest thing-location t8-8 thing-on-top-of ceiling thing-weight light)
  (che3 chest-name green-chest chest-contents blue-key chest-unlocked-by red-key)
  (thi8 thing-name red-key thing-location t1-3 thing-weight light thing-on-top-of floor)
  (Goal0 goal-is-to-action eat goal-is-to-argument1 bananas))