((guest1 guest_name n1 guest_sex m guest_hobby h3)
(guest1 guest_name n1 guest_sex m guest_hobby h2)
(guest2 guest_name n2 guest_sex m guest_hobby h2)
(guest2 guest_name n2 guest_sex m guest_hobby h3)
(guest3 guest_name n3 guest_sex m guest_hobby h1)
(guest3 guest_name n3 guest_sex m guest_hobby h2)
(guest3 guest_name n3 guest_sex m guest_hobby h3)
(guest4 guest_name n4 guest_sex f guest_hobby h3)
(guest4 guest_name n4 guest_sex f guest_hobby h2)
(guest5 guest_name n5 guest_sex f guest_hobby h1)
(guest5 guest_name n5 guest_sex f guest_hobby h2)
(guest5 guest_name n5 guest_sex f guest_hobby h3)
(guest6 guest_name n6 guest_sex f guest_hobby h3)
(guest6 guest_name n6 guest_sex f guest_hobby h1)
(guest6 guest_name n6 guest_sex f guest_hobby h2)
(guest7 guest_name n7 guest_sex f guest_hobby h3)
(guest7 guest_name n7 guest_sex f guest_hobby h2)
(guest8 guest_name n8 guest_sex m guest_hobby h3)
(guest8 guest_name n8 guest_sex m guest_hobby h1)
(ls last_seat 8)
(count c 1)
(context state start))