((Guest name n1 sex f hobby h3)
(Guest name n1 sex f hobby h1)
(Guest name n1 sex f hobby h2)
(Guest name n2 sex f hobby h3)
(Guest name n2 sex f hobby h2)
(Guest name n3 sex m hobby h1)
(Guest name n3 sex m hobby h3)
(Guest name n4 sex m hobby h2)
(Guest name n4 sex m hobby h1)
(Guest name n5 sex m hobby h2)
(Guest name n5 sex m hobby h3)
(Guest name n6 sex m hobby h2)
(Guest name n6 sex m hobby h1)
(Guest name n7 sex f hobby h2)
(Guest name n7 sex f hobby h1)
(Guest name n7 sex f hobby h3)
(Guest name n8 sex f hobby h3)
(Guest name n8 sex f hobby h2)
(Guest name n9 sex f hobby h1)
(Guest name n9 sex f hobby h3)
(Guest name n9 sex f hobby h2)
(Guest name n10 sex m hobby h2)
(Guest name n10 sex m hobby h3)
(Guest name n11 sex m hobby h3)
(Guest name n11 sex m hobby h2)
(Guest name n11 sex m hobby h1)
(Guest name n12 sex m hobby h3)
(Guest name n12 sex m hobby h1)
(Guest name n13 sex m hobby h2)
(Guest name n13 sex m hobby h3)
(Guest name n13 sex m hobby h1)
(Guest name n14 sex f hobby h3)
(Guest name n14 sex f hobby h1)
(Guest name n15 sex f hobby h3)
(Guest name n15 sex f hobby h1)
(Guest name n15 sex f hobby h2)
(Guest name n16 sex f hobby h3)
(Guest name n16 sex f hobby h2)
(Guest name n16 sex f hobby h1)
(Last seat 16)
(Count c 1)
(context state start)) 

