((Guest name n1 sex m hobby h3)
(Guest name n1 sex m hobby h2)
(Guest name n2 sex m hobby h2)
(Guest name n2 sex m hobby h3)
(Guest name n3 sex m hobby h1)
(Guest name n3 sex m hobby h2)
(Guest name n3 sex m hobby h3)
(Guest name n4 sex f hobby h3)
(Guest name n4 sex f hobby h2)
(Guest name n5 sex f hobby h1)
(Guest name n5 sex f hobby h2)
(Guest name n5 sex f hobby h3)
(Guest name n6 sex f hobby h3)
(Guest name n6 sex f hobby h1)
(Guest name n6 sex f hobby h2)
(Guest name n7 sex f hobby h3)
(Guest name n7 sex f hobby h2)
(Guest name n8 sex m hobby h3)
(Guest name n8 sex m hobby h1)
(Last seat 8)
(Count c 1)
(context state start)) 
